export const ENABLED_MARKETS = [
  "1x2",
  "double_chance",
  "btts",
  "over_under",
  "handicap",
];

/** Form fields */
export const formFields = {
  "1x2": [
    {
      name: "homeScore",
      type: "number",
      label: "Home Score (W1)",
      min: 0,
    },
    {
      name: "awayScore",
      type: "number",
      label: "Away Score (W2)",
      min: 0,
    },
    {
      name: "result",
      type: "select",
      label: "Result",
      required: true,
      options: [
        { label: "W1 (home)", value: "1" },
        { label: "X (draw)", value: "X" },
        { label: "W2 (away)", value: "2" },
      ],
    },
    {
      name: "odds",
      type: "number",
      label: "Odds",
      step: "0.01",
      required: true,
      min: 0,
    },
    {
      name: "stake",
      type: "number",
      label: "Stake",
      default: "100",
      step: "1",
      // disabled: true,
    },
  ],
  double_chance: [
    {
      name: "homeScore",
      type: "number",
      label: "Home Score (W1)",
      min: 0,
    },
    {
      name: "awayScore",
      type: "number",
      label: "Away Score (W2)",
      min: 0,
    },
    {
      name: "result",
      type: "select",
      label: "Select",
      required: true,
      options: [
        { label: "1X (home or draw)", value: "1X" },
        { label: "12 (home or away)", value: "12" },
        { label: "X2 (away or draw)", value: "X2" },
      ],
    },
    {
      name: "odds",
      type: "number",
      label: "Odds",
      step: "0.01",
      required: true,
      min: 0,
    },
    {
      name: "stake",
      type: "number",
      label: "Stake",
      default: "100",
      step: "1",
      // disabled: true,
    },
  ],
  handicap: [
    {
      name: "team",
      type: "select",
      label: "Select Team",
      required: true,
      options: [
        { label: "Home", value: "home" },
        { label: "Away", value: "away" },
      ],
    },
    {
      name: "handicap",
      type: "select",
      label: "Handicap",
      default: "0",
      options: [
        { label: "-6", value: "-6" },
        { label: "-5.75", value: "-5.75" },
        { label: "-5.5", value: "-5.5" },
        { label: "-5.25", value: "-5.25" },
        { label: "-5", value: "-5" },
        { label: "-4.75", value: "-4.75" },
        { label: "-4.5", value: "-4.5" },
        { label: "-4.25", value: "-4.25" },
        { label: "-4", value: "-4" },
        { label: "-3.75", value: "-3.75" },
        { label: "-3.5", value: "-3.5" },
        { label: "-3.25", value: "-3.25" },
        { label: "-3", value: "-3" },
        { label: "-2.75", value: "-2.75" },
        { label: "-2.5", value: "-2.5" },
        { label: "-2.25", value: "-2.25" },
        { label: "-2", value: "-2" },
        { label: "-1.75", value: "-1.75" },
        { label: "-1.5", value: "-1.5" },
        { label: "-1.25", value: "-1.25" },
        { label: "-1", value: "-1" },
        { label: "0 (Level)", value: "0" },
        { label: "+1", value: "1" },
        { label: "+1.25", value: "1.25" },
        { label: "+1.5", value: "1.5" },
        { label: "+1.75", value: "1.75" },
        { label: "+2", value: "2" },
        { label: "+2.25", value: "2.25" },
        { label: "+2.5", value: "2.5" },
        { label: "+2.75", value: "2.75" },
        { label: "+3", value: "3" },
        { label: "+3.25", value: "3.25" },
        { label: "+3.5", value: "3.5" },
        { label: "+3.75", value: "3.75" },
        { label: "+4", value: "4" },
        { label: "+4.25", value: "4.25" },
        { label: "+4.5", value: "4.5" },
        { label: "+4.75", value: "4.75" },
        { label: "+5", value: "5" },
        { label: "+5.25", value: "5.25" },
        { label: "+5.5", value: "5.5" },
        { label: "+5.75", value: "5.75" },
        { label: "+6", value: "6" },
      ],
      required: true,
    },
    {
      name: "homeScore",
      type: "number",
      label: "Home Score",
      default: "0",
      min: 0,
    },
    {
      name: "awayScore",
      type: "number",
      label: "Away Score",
      default: "0",
      min: 0,
    },
    {
      name: "odds",
      type: "number",
      label: "Odds",
      step: "0.01",
      required: true,
      min: 0,
    },
    {
      name: "stake",
      type: "number",
      label: "Stake",
      default: "100",
      step: "1",
      // disabled: true,
    },
  ],
  btts: [
    {
      name: "homeScore",
      type: "number",
      label: "Home Score (W1)",
      min: 0,
      required: true,
    },
    {
      name: "awayScore",
      type: "number",
      label: "Away Score (W2)",
      min: 0,
      required: true,
    },
    {
      name: "btts",
      type: "select",
      label: "Both team to score",
      required: true,
      options: [
        { label: "Yes", value: "yes" },
        { label: "No", value: "no" },
      ],
    },
    {
      name: "odds",
      type: "number",
      label: "Odds",
      step: "0.01",
      required: true,
      min: 0,
    },
    {
      name: "stake",
      type: "number",
      label: "Stake",
      default: "100",
      step: "1",
      // disabled: true,
    },
  ],
  over_under: [
    {
      name: "homeScore",
      type: "number",
      label: "Home Score (W1)",
      min: 0,
    },
    {
      name: "awayScore",
      type: "number",
      label: "Away Score (W2)",
      min: 0,
    },
    {
      name: "result",
      type: "select",
      label: "Select",
      required: true,
      default: "over_0.5",
      options: [
        { label: "Under (5.5)", value: "under_5.5" },
        { label: "Under (5)", value: "under_5" },
        { label: "Under (4.5)", value: "under_4.5" },
        { label: "Under (4)", value: "under_4" },
        { label: "Under (3.5)", value: "under_3.5" },
        { label: "Under (3)", value: "under_3" },
        { label: "Under (2.5)", value: "under_2.5" },
        { label: "Under (2)", value: "under_2" },
        { label: "Under (1.5)", value: "under_1.5" },
        { label: "Under (1)", value: "under_1" },
        { label: "Under (0.5)", value: "under_0.5" },
        { label: "Over (0.5)", value: "over_0.5" },
        { label: "Over (1)", value: "over_1" },
        { label: "Over (1.5)", value: "over_1.5" },
        { label: "Over (2)", value: "over_2" },
        { label: "Over (2.5)", value: "over_2.5" },
        { label: "Over (3)", value: "over_3" },
        { label: "Over (3.5)", value: "over_3.5" },
        { label: "Over (4)", value: "over_4" },
        { label: "Over (4.5)", value: "over_4.5" },
        { label: "Over (5)", value: "over_5" },
        { label: "Over (5.5)", value: "over_5.5" },
      ],
    },
    {
      name: "odds",
      type: "number",
      label: "Odds",
      step: "0.01",
      required: true,
      min: 0,
    },
    {
      name: "stake",
      type: "number",
      label: "Stake",
      default: "100",
      step: "1",
      // disabled: true,
    },
  ],
  half_time_fill_time: [{}],
  either_half_wins: [{}],
};
